version: '4.0'
services:
  transferencia-service:
    build: .
    ports:
      - "8080:8080"
  wiremock:
    image: rodolpheche/wiremock:2.30.1
    ports:
      - "9191:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-networks
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - aw-networks
networks:
  aw-networks:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: